# CONFIG_CONSTANTS
DB_HOST_NAME = "DB_HOST_NAME"
DB_PORT = "DB_PORT"
DB_AUTH_SOURCE = "DB_AUTH_SOURCE"
DB_NAME = "DB_NAME"
DB_USER_NAME = "DB_USER_NAME"
DB_PASSWORD = "DB_PASSWORD"
DB_SSL_CERTIFICATE_LOCATION = "DB_SSL_CERTIFICATE_LOCATION"
EMAIL = "EMAIL"
EMAIL_PASSWORD = "EMAIL_PASSWORD"
PUBLIC_RSA_KEY = "PUBLIC_RSA_KEY"
PRIVATE_RSA_KEY = "PRIVATE_RSA_KEY"
URL_GENERATOR_SECRET = "URL_GENERATOR_SECRET"
FERNET_KEY = "FERNET_KEY"
MAIL_SERVER = "MAIL_SERVER"
MAIL_PORT = "MAIL_PORT"
MAIL_USERNAME = "MAIL_USERNAME"
MAIL_PASSWORD = "MAIL_PASSWORD"
MAIL_USE_TLS = "MAIL_USE_TLS"
MAIL_USE_SSL = "MAIL_USE_SSL"
EMAIL_SALT = "EMAIL_SALT"
EXECUTOR_TYPE = "EXECUTOR_TYPE"
EXECUTOR_MAX_WORKERS = "EXECUTOR_MAX_WORKERS"
EXECUTOR_PROPAGATE_EXCEPTIONS = "EXECUTOR_PROPAGATE_EXCEPTIONS"
TOKEN_SECRET_KEY = "TOKEN_SECRET_KEY"
REDIS_HOST = "REDIS_HOST"
REDIS_PORT = "REDIS_PORT"
JWT_SECRET_KEY = "JWT_SECRET_KEY"
JWT_TOKEN_LOCATION = "JWT_TOKEN_LOCATION"
JWT_ACCESS_TOKEN_EXPIRES = "JWT_ACCESS_TOKEN_EXPIRES"
JWT_ACCESS_TOKEN_EXPIRES_TIME_MINUTES = 60
JWT_ACCESS_TOKEN_EXPIRES_TIME_HOURS = 1
JSON_TOKEN_IDENTIFIER = "jti"
BLOCKCHAIN_URL = "BLOCKCHAIN_URL"
ML_PATH = "ML_PATH"
# CONFIG_CONSTANTS


# APP_CONSTANTS
ENV_PROD = "production"
ENV_DEV = "development"
DB_CONFIG = "db_config"
WORKING_ENV = "working_env"
ENVIRONMENT = "ENV"
LOGGING_FILE = "logging_file"
LOG_FILE_NAME = "log-config.conf"
MAX_NUMBER_OF_THREAD = 256
AUTHORIZATION = "Authorization"
USER_API_ACCESS_TOKEN = "access_token"
AVAILABLE = "Available"
BOOKED = "Booked"
REQUEST_APPOINTMENT = "Request Appointment"
CREATED = "Created"
INITIATED = "Initiated"
WAITING_INSURANCE_APPROVAL = "Waiting for Insurance Approval"
APPROVED = "Approved"
REJECTED = "Rejected"
INSURANCE = "Insurance"
SELF = "Self"
COMPLETED = "Completed"
# APP_CONSTANTS


# PRODUCTION_HOST_CONSTANTS
PROD_HOST_NAME = "flask-server"
# PRODUCTION_HOST_CONSTANTS


# DATABASE_CONSTANTS
DATABASE_HMS = "HospitalManagementSystem"
DATABASE_FILE_STORAGE_hms = "file_storage_hms"
COLLECTION_USERS = "users"
COLLECTION_APPOINTMENTS = "appointments"
COLLECTION_INSURANCE = "insurance"
COLLECTION_LAB = "lab"
COLLECTION_PRESCRIPTION = "prescription"
COLLECTION_DIAGNOSIS = "Diagnosis"
COLLECTION_TRANSACTION = "transaction"
COLLECTION_FS_FILES = "fs.files"
USER_ID = "user_id"
COLLECTION_ADMIN_LOG = "admin_log"
# DATABASE_CONSTANTS


# REDIS CONSTANT
REDIS_OTP_EXTENDED_KEY = "_otp"
REDIS_OTP_KEY_TIMEOUT = 600  # 10 minutes
# REDIS CONSTANT


# RESPONSE_OBJECT_CONSTANTS
STATUS = "Status"
MESSAGE = "Message"
DATA = "Data"
DIAGNOSIS_DATA = "DiagnosisData"
PRESCRIPTION_DATA = "PrescriptionData"
LAB_DATA = "LabData"
TOKEN = "Token"
STATUS_SUCCESS = "Success"
STATUS_FAILURE = "Failure"
STATUS_APPROVED = "Approved"
MESSAGE_USER_EXIST = "User exist"
MESSAGE_USER_NOT_EXIST = "User not exist"
MESSAGE_USER_PASSWORD_INCORRECT = "User password incorrect"
MESSAGE_USER_PASSWORD_UPDATE_SUCCESSFULLY = "User password update successfully"
MESSAGE_USER_LOGIN = "User login successfully"
MESSAGE_USER_ADDED = "User registered successfully"
MESSAGE_NOT_APPLICABLE = "Not Applicable"
MESSAGE_USER_NOT_VERIFIED = "User not verified"
MESSAGE_USER_NOT_APPROVED = "User not approved by admin"
MESSAGE_USER_INFO_UPDATED = "User information updated successfully"
MESSAGE_BACKEND_API_ERROR = "Backend API error"
MESSAGE_INCORRECT_OTP = "Incorrect OTP"
MESSAGE_OTP_SEND_SUCCESSFULLY = "OTP send successfully"
MESSAGE_OTP_CONFIRMED_SUCCESSFULLY = "OTP confirm successfully"
MESSAGE_OTP_EXPIRED = "OTP Expired"
MESSAGE_ACCESS_REVOKED = "Access token revoked"
MESSAGE_NO_APPOINTMENT_AVAILABLE = "No appointments Available"
MESSAGE_NO_CURRENT_APPOINTMENT = "No Current Appointment"
MESSAGE_SLOT_NOT_AVAILABLE = "Slot not available"
MESSAGE_APPOINTMENT_BOOKED_SUCCESSFULLY = "Appointment booked successfully"
MESSAGE_APPOINTMENT_CANCELLED_SUCCESSFULLY = "Appointment cancelled"
MESSAGE_INSURANCE_POLICY_ADDED = "Added Insurance Policy to patient"
MESSAGE_INSURANCE_INFO_UPDATED = " Insurance info updated successfully"
MESSAGE_CHATBOT_SUCCESS = "Got successful reply"
MESSAGE_CHATBOT_FAILURE = "chatbot failed to reply. Try again!"
MESSAGE_DIAGNOSIS_ADDED = "Diagnosis record added successfully"
MESSAGE_DIAGNOSIS_UPDATED = "Diagnosis record updated successfully"
MESSAGE_ERROR_APPOINTMENT = "Error getting appointments"
MESSAGE_ERROR_GETTING_USER_DATA = "Error in getting user data"
MESSAGE_NO_APPROVAL_PENDING = "You have no new user approval pending. Cheers!"
MESSAGE_USER_APPROVED_OR_REJECT = "User approved or rejected successfully"
MESSAGE_NO_ACTIVITIES_FROM_ANY_USER = "No activities from any users"
MESSAGE_NO_DIAGNOSIS_RECORDS_FOUND = "No Diagnosis Record Found"
MESSAGE_NO_LAB_REPORT_REQUEST_PENDING = "No Lab Report request pending"
MESSAGE_NO_LAB_RECORDS_FOUND = "No lab records found for the appointment id"
MESSAGE_NO_LAB_RECORDS_FOUND_WITH_RECORD_ID = "No lab records found for the record id"
MESSAGE_CREATED_UPDATED_LAB_RECORD = "Created/Updated lab record successfully"
MESSAGE_DELETED_LAB_RECORD_SUCCESSFULLY = "Deleted lab record successfully"
MESSAGE_USER_RECORD_DELETED_SUCCESSFULLY = "User records deleted successfully"
MESSAGE_ADMIN_ACCOUNT_DELETE = "Can't delete admin account"
MESSAGE_INSURANCE_NOT_FOUND = "Insurance data not found please create one"
MESSAGE_NO_NEW_TRANSACTION_AVAILABLE = "No new transactions available"
MESSAGE_TRANSACTION_NOT_AVAILABLE = "No transaction with this ID available"
MESSAGE_INITIATED_SUCCESSFULLY = "Transaction initiated successfully."
MESSAGE_INITIATED_FAILED = "Transaction initiation failed."
MESSAGE_NO_TRANSACTION_TO_APPROVE = "No transactions to approve."
MESSAGE_CHANGE_TRANSACTION_STATUS = "Successfully change status of the transaction to: "
MESSAGE_FAILED_CHANGE_TRANSACTION_STATUS = "Failed to change transaction state."
MESSAGE_MEDICAL_DATA_FOUND = "Medical Record Found."
MESSAGE_NO_MEDICAL_DATA_FOUND = "NO Medical Record Found."
MESSAGE_NO_TRANSACTIONS_AVAILABLE = "No transactions available."
MESSAGE_TRANSACTIONS_RETRIEVED = "Transactions retrieved"
# RESPONSE_OBJECT_CONSTANTS


# OTHER KEYS
OTP_KEY = "otp"
# OTHER KEYS


# MISC
RESPONSE_FAILURE = {STATUS: STATUS_FAILURE, MESSAGE: MESSAGE_BACKEND_API_ERROR}
# MISC
